# Generated by Django 3.0.3 on 2020-03-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='TITLE', max_length=100)),
                ('description', models.TextField(db_column='DESCRIPTION')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('Modified_at', models.DateTimeField(auto_now=True, db_column='MODIFIED_AT')),
            ],
        ),
    ]
