# Generated by Django 3.0.3 on 2020-03-02 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('-created_at',), 'verbose_name': 'subject'},
        ),
    ]
